name 'evenup-curator'
version '1.0.1'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Installs elasticsearch curator and schedules cron jobs'
description 'Installs elasticsearch curator and manages cron jobs for logstash elasticsearch index maintainence'
source 'https://github.com/evenup/evenup-curator'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
